language: cpp
dist: xenial

# compilers to add to build matrix

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"


# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake ../example

script:
  - cmake --build . 
