version: '{build}'

image: 
  - Visual Studio 2019
  - Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      GENERATOR: "Visual Studio 16 2019"
      CONFIG: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      GENERATOR: "Visual Studio 16 2019"
      CONFIG: Release
      
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      GENERATOR: "Visual Studio 15 2017"
      CONFIG: Debug
      
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      GENERATOR: "Visual Studio 15 2017"
      CONFIG: Release      

build_script:
  - ps: cd example
  - cmake "-G%GENERATOR%" -H. -B_builds -DENABLE_TESTING=1
  - cmake --build _builds --config "%CONFIG%"
